name: predicting-employee-attrition
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scikit-learn
  - xgboost
  - shap
  - jupyter
  - ipykernel
  - scipy
  - tqdm
  - pip
  - pip:
      - category_encoders
